baseURL = "/"
languageCode = "en-us"
title = "Axiom Dev - Blog"
description = "A blog following my proects & my path towards a career in CS"
theme = "min_night"
disqusShortname = ""
googleAnalytics = "UA-138990401-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Timothy Dixon"
    description = "A blog following my projects & my  path towards a career in CS"
    logo = "profile.png"
    twitterAuthor = ""
    githubUsername = "Tim-Dixon"
    accent = "#1149ff" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

[[menu.main]]
    url = "https://tim-dixon.github.io/github-web-portfolio/"
    name = "Git-Hub Portfolio"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:timothy.b.dixon@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Tim-Dixon"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/timothy-b-dixon/"
    name = "linkedin"
    weight = 3
